### ISSUE TITLE
Snippet Request

### ISSUE THREAD

**Issue by Linxford** [zyllus17/flutter-snippets#35]
Just update it to add const to constant structures

**Comment by zyllus17** [comment]
@wisdak  I have thought about adding const before each widget and it would best to use the IDE to add the `const` instead of providing them directly with the snippets.

**Reason** - If a Widget like Center is called inside a Container and it comes with const, then the children widget will throw and error like this. So its best to use the IDE help(the bulb button on the left) to assign const everywhere in one go as it is smarter and knows where const can be applied.

<img width="727" alt="Screenshot 2023-01-13 at 10 52 24 AM" src="https://user-images.githubusercontent.com/50977126/212243569-39813461-4a79-4bbc-9ffc-b3a19adc7384.png">

**Comment by zyllus17** [comment]
Hope this helps. Closing the issue for now.

**Comment by Linxford** [comment]
alright, i guess is ok now,

thanks
